### PR TITLE
Bring up to date with druid v0.8

### PR DESCRIPTION
**Pull request by derekdreery**

### CODE REVIEW

**Comment by derekdreery** [comment]
Really don't understand clippy - it's failing on some code that **doesn't exist**.

**Comment by xStrom** [comment]
`cargo clippy --all-targets --all-features` seems to still give about a dozen complaints.

**Comment by derekdreery** [comment]
@xStrom thanks, I've modified the CI to include examples in the clippy test.

**Review by xStrom — APPROVED** [review]
The code changes (*which are mostly `clippy` anyway*) look good from the surface.

I played around with a bunch of examples, although not with all of them. Looks reasonable overall.

I did find the `dropdown` example in a weird state, probably broken. However the dropdown in the `select` example works ok. So not sure what's going on there, but I don't think that should be a block for this PR.

This whole nursery repo exists to allow for a lower quality threshold, so I say ship it! 🚀

**Pull request merged**
