### PR TITLE
Add on_command widget

### PR DESCRIPTION
**Pull request by Maan2003**

### CODE REVIEW

**Review by derekdreery — APPROVED** [review]
Looks useful.

**Comment by derekdreery** [comment]
I've merged your PR with master but I did it in github so it isn't tested. Will check and fix if it breaks build.

**Comment by Maan2003** [comment]
huh weird, `cargo check` is fine, but `cargo clippy` is not :thinking: . Also it is unrelated to this PR. and how #69 passed the test

**Comment by derekdreery** [comment]
Clippy error will be from an auto merge, we can fix it with a follow-up PR

**Pull request merged**
