### PR TITLE
making some updates to navigator widget and adding example

### PR DESCRIPTION
**Pull request by arthmis**
https://github.com/linebender/druid-widget-nursery/issues/15

### CODE REVIEW

**Comment by derekdreery** [comment]
Thanks very much for this! I think there might be a little problem with the example (see the "test" part of the CI for the error). If I'm wrong let me know and I'll get it merged.

**Comment by arthmis** [comment]
I see, I swear I pulled in the latest master. I'll have to update druid and fix the issues.

**Comment by arthmis** [comment]
Ok I think that covers the issues introduced by my code.

**Review by derekdreery — APPROVED** [review]
LGTM

**Pull request merged**
