### PR TITLE
ThemeLoader widget

### PR DESCRIPTION
**Pull request by cmyr**
This is an experiment in live-reloading themes from disk.

Useage is hopfully explained by the docs in theme_loader/mod.rs.
The basic idea is that you combine a set of keys into a 'theme'
with a macro, and then pass that theme and a path to a ThemeLoader
widget. This widget then loads the file at that path, and attempts
to parse out the expected keys, adding them to the env if successful.

For live-reloading, you need to enable the 'notify' feature.

This requires https://github.com/linebender/druid/pull/1517, but that shouldn't be too hard to merge.

cc @eliheuer, this is a little present for you, I'll add support in runebender shortly.

### CODE REVIEW

**Comment by derekdreery** [comment]
Woop. I'm going to set up some CI over the weekend. The idea is that merging won't be conditional on passing CI, but it will give us info on if stuff needs fixing up.

**Review by derekdreery — APPROVED** [review]

**Comment by cmyr** [comment]
I'm running into problems actually using  this, because we have a pinned version of druid; it means another crate that is using druid that isn't pinned to an identical commit will get compilation errors. I think I'm going to revert this and make it a new crate inside the runebender repo, for now.

**Comment by derekdreery** [comment]
Alternatively we could just relax the particular rev thing in this crate. I'm not sure it adds much.

**Comment by cmyr** [comment]
it will only be an issue if someone wants to use a widget from this crate with a newer version of druid that doesn't work with the version we're using in this crate. :/

**Comment by derekdreery** [comment]
I'd encourage cut'n'paste of code ATM as well.

**Pull request merged**
